### ISSUE TITLE
Another FMA implementation

### ISSUE THREAD

**Issue by TuomLarsen** [smasher164/fma#3]
Since you are comparing soft FMAs of MUSL and BSD, I thought you would find interesting another implementation by Fabrice Bellard in his [SoftFP](https://bellard.org/softfp/), see `softfp_template.h/fma_sf()`.

**Comment by smasher164** [comment]
This is indeed very interesting. I will take a crack at the implementation and compare it with the others. Thanks!

**Comment by smasher164** [comment]
4ef5b87c251d4224e3f3fef4fcc731462d1a6720 implements Bellard's version. Preliminary benchmarking reveals it to run at the same speed as MUSL's, but the Bellard translation uses ~50 more lines of code.
This is unfair, since Bellard reimplements basic operations like NaN checking and normalization on the integer representation of the float. MUSL however, makes use of the standard library and underlying FPU implementation more, but there may be room for refactoring.

**Comment by TuomLarsen** [comment]
Thank you for the thorough comparative analysis! Very interesting, indeed.
